name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  clang-format:
    name: Check clang-format
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm git clang diffutils
          git config --global --add safe.directory $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
      - uses: fcitx/github-actions@clang-format
  check:
    name: Build and test
    needs: clang-format
    runs-on: ubuntu-latest
    container: archlinux:latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc, clang]
        include:
          - compiler: gcc
            cxx_compiler: g++
          - compiler: clang
            cxx_compiler: clang++
    env:
      CC: ${{ matrix.compiler }}
      CXX: ${{ matrix.cxx_compiler }}
    steps:
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm base-devel clang cmake ninja extra-cmake-modules fmt libuv boost git go
      - uses: actions/checkout@v4
        with:
          repository: fcitx/fcitx5
          path: fcitx5
      - name: Cache fcitx5 data files
        uses: actions/cache@v4
        with:
          path: 'fcitx5/**/*.tar.*'
          key: ${{ runner.os }}-${{ hashFiles('fcitx5/src/modules/spell/CMakeLists.txt')
            }}
      - name: Build and Install fcitx5
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5
          cmake-option: >-
            -DENABLE_KEYBOARD=Off -DENABLE_X11=Off -DENABLE_WAYLAND=Off -DENABLE_ENCHANT=Off
            -DENABLE_DBUS=Off -DENABLE_SERVER=Off -DENABLE_EMOJI=Off -DUSE_SYSTEMD=Off
      - uses: actions/checkout@v4
        with:
          path: fcitx5-bamboo
          submodules: true
      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: cpp,go
          source-root: fcitx5-bamboo
      - name: Build and Install fcitx5-bamboo
        uses: fcitx/github-actions@cmake
        with:
          path: fcitx5-bamboo
      - name: Test
        run: |
          ctest --test-dir fcitx5-bamboo/build
      - name: CodeQL Analysis
        uses: github/codeql-action/analyze@v2
